[workspace]
resolver = "2"
members = [
    "crates/science-diagnostics",
    "crates/science-lexer",
    "crates/science-parser",
    "crates/science-fmt",
    "crates/science-testkit",
    "crates/science-resolve",
    "crates/science-types",
    "crates/science-db",
    "crates/science-rt",
    "crates/science-codegen",
    "crates/sciencec",
]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
science-diagnostics = { path = "crates/science-diagnostics" }
science-lexer = { path = "crates/science-lexer" }
science-parser = { path = "crates/science-parser" }
science-fmt = { path = "crates/science-fmt" }
science-testkit = { path = "crates/science-testkit" }
science-resolve = { path = "crates/science-resolve" }
science-types = { path = "crates/science-types" }
science-db = { path = "crates/science-db" }
science-rt = { path = "crates/science-rt" }
science-codegen = { path = "crates/science-codegen" }
sciencec = { path = "crates/sciencec" }
insta = "1"
